project:
  type: website
  resources:
    - "images/*.webp"

website:
  title: "ISSS608-VAA"
  navbar:
    left:
      - text: "<img src='/images/dory.png' width='40' height='40' style='margin-right: 5px;'> 
      Hands-on Exercise"
        menu:
          - text: "HO1_A Layered Grammar of Graphics: ggplot2 methods"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          
          - text: "HO2_Beyond ggplot2 Fundamentals"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
            
          - text: "HO3_Interactive Data Visualisation with R"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
            
          - text: "HO4_Animated Statistical Graphics with R ⭐"
            href: "Hands-on_Ex/Hands-on_Ex03b/Hands-on_Ex03b.html"
            
          - text: "HO5_Visualising Distribution"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
            
          - text: "HO6_Visual Statistical Analysis"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04b.html"
          
          - text: "HO7_Visualising Uncertainty ⭐"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04c.html"
            
          - text: "HO8_Funnel Plots for Fair Comparisons"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04d.html"
            
      - text: "<img src='/images/shark.png' width='40' height='40' style='margin-right: 5px;'> 
      Take-home Exercise"
        menu:
          - text: "Take-home Exercise 1"
          
      - text: "<img src='/images/black.png' width='40' height='40' style='margin-right: 5px;'> 
      Real-world Project"
        menu:
          - text: "Customer Segmentation"
            href: "Analytics_Project/Customer_Segmentation/Customer_Segmentation.html"
    
    
    right:
      - text: "Home"
        href: index.qmd
        
      - text: "About"
        href: about.qmd
        
format:
  html:
    theme: superhero
    css: styles.css
    toc: true

editor: visual

