project:
  type: website
  resources:
    - "images/*.webp"

website:
  title: "HAUKIMNG"
  navbar:
    left:
      - text: "<img src='/images/dory.png' width='40' height='40' style='margin-right: 5px;'> 
      Hands-on Exercise"
        menu:
          - text: "HO1_A Layered Grammar of Graphics: ggplot2 methods"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          
          - text: "HO2_Beyond ggplot2 Fundamentals"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
            
          - text: "HO3_Interactive Data Visualisation with R"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
            
          - text: "HO4_Animated Statistical Graphics with R ⭐"
            href: "Hands-on_Ex/Hands-on_Ex03b/Hands-on_Ex03b.html"
            
          - text: "HO5_Visualising Distribution"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
            
          - text: "HO6_Visual Statistical Analysis"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04b.html"
          
          - text: "HO7_Visualising Uncertainty ⭐"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04c.html"
            
          - text: "HO8_Funnel Plots for Fair Comparisons"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04d.html"
            
          - text: "HO9_Creating Ternary Plot with R"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05a.html"
            
          - text: "HO10_Visual Correlation Analysis ⭐"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05b.html"
            
          - text: "HO11_Heatmap for Visualising and Analysing Multivariate Data"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05c.html"
            
          - text: "HO12_Visual Multivariate Analysis with Parallel Coordinates Plot"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05d.html"
            
          - text: "HO13_Modelling, Visualising and Analysing Network Data with R"
            href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07a.html"
            
          - text: "HO14_Visualising and Analysing Text Data with R: tidytext methods"
            href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07b.html"
            
          - text: "HO15_Visualising and Analysing Time-oriented Data"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html"
            
          - text: "HO16_Choropleth Mapping with R"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09a.html"
            
          - text: "HO17_Visualising Geospatial Point Data"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09b.html"
          
          - text: "HO18_Analytical Mapping"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09c.html"
            
          - text: "HO19_Information Dashboard Design: R methods"
            href: "Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.html"
            
      - text: "<img src='/images/shark.png' width='40' height='40' style='margin-right: 5px;'> 
      Take-home Exercise"
        menu:
          - text: "EX1: Technical Report-Unmasking Motor Insurance Risk Drivers"
            href: "Take-home_Ex/Take-home_Ex01/Technical_Report.html"
            
          - text: "EX1: Executive Summary-Unmasking Motor Insurance Risk Drivers"
            href: "Take-home_Ex/Take-home_Ex01/Executive_Summary.html"
            
          - text: "EX2: VAST Challenge 2026-Anomalous Post Investigation"
            href: "Take-home_Ex/Take-home_Ex02/MC2.html"
            
          
      - text: "<img src='/images/black.png' width='40' height='40' style='margin-right: 5px;'> 
      Real-world Project"
        menu:
          - text: "Customer Segmentation"
            href: "Analytics_Project/Customer_Segmentation/Customer_Segmentation.html"
    
    
    right:
      - text: "Home"
        href: index.qmd
        
      - text: "About"
        href: about.qmd
        
format:
  html:
    theme: superhero
    css: styles.css
    toc: true

editor: visual

