---
title: "Hands-on Exercise 1"
author: "Nguyen Kim Hau"
date: "April 16, 2026"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---

# Getting Started

## Install and launching R packages

The code chunk below uses p_load() of pacman package to check if tidyverse packages are installed in the computer. If they are, then they will be launched into R.

```{r}
pacman::p_load(tidyverse)

```

## Importing the data

```{r}
exam_data <- read_csv("data/Exam_data.csv")
```

```{r}
head(exam_data, n = 10)
```

# Plotting different chart types

## Bar chart

```{r}
p1 <- ggplot(data=exam_data, 
       aes(x=RACE)) +
  geom_bar() +
  ggtitle("Number of students by Nationalities")
p1

```

```{r}
p1 +
  coord_flip()
```

```{r}
p1 + theme_linedraw()

```

## Histogram chart

```{r}
ggplot(data=exam_data, aes(x = MATHS)) +
  geom_histogram(bins=10, 
                 boundary = 100,
                 color="black", 
                 fill="light blue") +
  ggtitle("Distribution of Maths scores")

```

```{r}
ggplot(data=exam_data, 
       aes(x = MATHS)) +
  geom_dotplot(binwidth=2.5,         
               dotsize = 0.5) +      
  scale_y_continuous(NULL,           
                     breaks = NULL)  +
  ggtitle("Distribution of Maths scores")
```

```{r}
ggplot(data=exam_data, 
       aes(x= MATHS, 
           fill = GENDER)) +
  geom_histogram(bins=20, 
                 color="grey30") +
  ggtitle("Stacked Distribution of Maths scores by Gender")
```

```{r}
ggplot(data=exam_data, 
       aes(x = MATHS, 
           colour = GENDER)) +
  geom_density() +
  ggtitle("Density of Maths scores by Gender")
```

## Box plot

```{r}
ggplot(data=exam_data, 
       aes(y = MATHS, 
           x= GENDER)) +
  geom_boxplot(notch=TRUE) +
  ggtitle("Boxplot of Maths scores by Gender")
```

## Violin plot

```{r}
ggplot(data=exam_data, 
       aes(y = MATHS, 
           x= GENDER)) +
  geom_violin() +
  ggtitle("Violin plot of Math scores by Gender")
```

## Scatter plot

```{r}
ggplot(data=exam_data, 
       aes(x= MATHS, 
           y=ENGLISH)) +
  geom_point() +
  geom_smooth(method=lm, 
              linewidth=0.5) +
  ggtitle("Scatter plot between Math and English scores")
```

```{r}
ggplot(data=exam_data, 
       aes(x= MATHS, y=ENGLISH)) +
  geom_point() +
  geom_smooth(method=lm, 
              size=0.5) +  
  coord_cartesian(xlim=c(0,100),
                  ylim=c(0,100)) +
  ggtitle("Scatter plot between Math and English scores, equal axis")
```

## Combination chart types

```{r}
ggplot(data=exam_data, 
       aes(y = MATHS, 
           x= GENDER)) +
  geom_boxplot() +                    
  geom_point(position="jitter", 
             size = 0.5) +
  ggtitle("Scatter and box plots of Math scores by Gender")
```

```{r}
ggplot(data=exam_data, 
       aes(y = MATHS, x= GENDER)) +
  geom_boxplot() +
  stat_summary(geom = "point",       
               fun = "mean",         
               colour ="red",        
               size=4)               
```

```{r}
ggplot(data=exam_data, 
       aes(x= MATHS)) +
  geom_histogram(bins=20) +
  facet_wrap(~ CLASS) +
  ggtitle("facet_wrap()")

```

```{r}
ggplot(data=exam_data, 
       aes(x= MATHS)) +
  geom_histogram(bins=20) +
  facet_grid(~ CLASS) +
  ggtitle("facet_grid()")
```
